/*
 * BookTypeInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itjob.view;

import java.awt.print.Book;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.itjob.dao.BookTypeDao;
import com.itjob.model.BookType;
import com.itjob.util.DButil;
import com.itjob.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class BookTypeInterFrm extends javax.swing.JInternalFrame {

	public DButil dButil = new DButil();

	public BookTypeDao bookTypeDao = new BookTypeDao();

	/** Creates new form BookTypeInterFrm */
	public BookTypeInterFrm() {
		initComponents();
		this.setLocation(500, 50);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		bookTypeTxt = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		bookTypeDescTxt = new javax.swing.JTextArea();
		jb_booktypeAdd = new javax.swing.JButton();
		Jb_Rest = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u6dfb\u52a0\u56fe\u4e66\u7c7b\u522b");

		jLabel1.setText("\u56fe\u4e66\u7c7b\u522b");

		jLabel2.setText("\u56fe\u4e66\u7c7b\u522b\u63cf\u8ff0");

		bookTypeTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			}
		});

		bookTypeDescTxt.setColumns(20);
		bookTypeDescTxt.setRows(5);
		jScrollPane1.setViewportView(bookTypeDescTxt);

		jb_booktypeAdd.setText("\u6dfb\u52a0");
		jb_booktypeAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_booktypeAddActionPerformed(evt);
			}
		});

		Jb_Rest.setText("\u91cd\u7f6e");
		Jb_Rest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Jb_RestActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(36, 36, 36)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jb_booktypeAdd)
																.addGap(85, 85,
																		85)
																.addComponent(
																		Jb_Rest)
																.addGap(159,
																		159,
																		159))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addGap(45, 45,
																		45)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						bookTypeTxt,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						212,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						212,
																						Short.MAX_VALUE))
																.addGap(60, 60,
																		60)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														bookTypeTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(63, 63, 63)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														87,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										30, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jb_booktypeAdd)
												.addComponent(Jb_Rest))
								.addGap(23, 23, 23)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void Jb_RestActionPerformed(java.awt.event.ActionEvent evt) {
		resetValue();

	}
	
	public void resetValue(){
		this.bookTypeTxt.setText("");
		this.bookTypeDescTxt.setText("");
	}

	private void jb_booktypeAddActionPerformed(java.awt.event.ActionEvent evt) {
		String bookTypeName = this.bookTypeTxt.getText();
		String bookTypeDesc = this.bookTypeDescTxt.getText();
		if (StringUtil.isEmpty(bookTypeName)) {
			JOptionPane.showMessageDialog(null, "图书类别不能为空");
			return;
		}
		BookType bookType = new BookType(bookTypeName, bookTypeDesc);
		Connection con = null;
		try {
			con = dButil.getCon();
			int result = bookTypeDao.addBookType(con, bookType);
			if (result == 1) {
				resetValue();
				JOptionPane.showMessageDialog(null, "图书类别添加成功");
				
			}else{
				JOptionPane.showMessageDialog(null, "图书类别添加失败");
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "图书类别添加失败");

			e.printStackTrace();
		}

	}


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton Jb_Rest;
	private javax.swing.JTextArea bookTypeDescTxt;
	private javax.swing.JTextField bookTypeTxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jb_booktypeAdd;
	// End of variables declaration//GEN-END:variables

}