/*
 * BookTypeManageInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.itjob.view;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

import com.itjob.dao.BookTypeManageDao;
import com.itjob.model.BookType;
import com.itjob.util.DButil;

/**
 *
 * @author  __USER__
 */
public class BookTypeManageInterFrm extends javax.swing.JInternalFrame {

	public DButil dButil = new DButil();

	public BookTypeManageDao bookTypeManageDao = new BookTypeManageDao();

	/** Creates new form BookTypeManageInterFrm */
	public BookTypeManageInterFrm() {
		initComponents();
		this.setLocation(500, 0);
		this.filltable(new BookType());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		bookTypeManageTxt = new javax.swing.JTextField();
		jBSearch = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		JtableModel = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jIdtxt = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jbookTypeNameTxt = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jBookTypeDesc = new javax.swing.JTextArea();
		jb_modify = new javax.swing.JButton();
		jb_delete = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u56fe\u4e66\u7c7b\u522b\u7ba1\u7406");

		jLabel1.setText("\u56fe\u4e66\u7c7b\u522b\uff1a");

		jBSearch.setText("\u67e5\u8be2");
		jBSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBSearchActionPerformed(evt);
			}
		});

		JtableModel.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "编号", "图书类别", "图书类别描述" }) {
			boolean[] canEdit = new boolean[] { false, false, true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(JtableModel);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u8868\u5355\u64cd\u4f5c"));
		jPanel1.setName("null");

		jLabel2.setText("\u7f16\u53f7:");

		jIdtxt.setEditable(false);
		jIdtxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jIdtxtActionPerformed(evt);
			}
		});

		jLabel3.setText("\u56fe\u4e66\u7c7b\u522b\u540d\u79f0:");

		jLabel4.setText("\u63cf\u8ff0");

		jBookTypeDesc.setColumns(20);
		jBookTypeDesc.setRows(5);
		jScrollPane2.setViewportView(jBookTypeDesc);

		jb_modify.setText("\u4fee\u6539");

		jb_delete.setText("\u5220\u9664");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jIdtxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												115,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabel3,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												76,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jbookTypeNameTxt,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												184,
																												Short.MAX_VALUE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jScrollPane2,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												401,
																												Short.MAX_VALUE)))
																		.addContainerGap())
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jb_modify)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				320,
																				Short.MAX_VALUE)
																		.addComponent(
																				jb_delete)
																		.addGap(21,
																				21,
																				21)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jIdtxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																jbookTypeNameTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(30, 30, 30)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jb_delete)
														.addComponent(jb_modify))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(68, 68,
																		68)
																.addComponent(
																		jLabel1)
																.addGap(30, 30,
																		30)
																.addComponent(
																		bookTypeManageTxt,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		195,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(65, 65,
																		65)
																.addComponent(
																		jBSearch))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(58, 58,
																		58)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						452,
																						Short.MAX_VALUE))))
								.addContainerGap(174, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(53, 53, 53)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		bookTypeManageTxt,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		jBSearch))
												.addComponent(jLabel1))
								.addGap(37, 37, 37)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										266,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jIdtxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jBSearchActionPerformed(java.awt.event.ActionEvent evt) {
		String bookTypeManageTxt = this.bookTypeManageTxt.getText();
		BookType bookType = new BookType();
		bookType.setBookTypeName(bookTypeManageTxt);
		filltable(bookType);

	}
	
	private void filltable(BookType bookType){
		DefaultTableModel dtm = (DefaultTableModel) this.JtableModel.getModel();
		dtm.setRowCount(0);
		Connection con = null;
		try {
			con = dButil.getCon();
			ResultSet rs = bookTypeManageDao.findBookType(con,bookType);
			while(rs.next()){
				Vector v = new Vector();
				v.add(rs.getString("id"));
				v.add(rs.getString("bookTypeName"));
				v.add(rs.getString("bookTypeDesc"));
				dtm.addRow(v);
			}
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			try {
				dButil.closeCon(con);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable JtableModel;
	private javax.swing.JTextField bookTypeManageTxt;
	private javax.swing.JButton jBSearch;
	private javax.swing.JTextArea jBookTypeDesc;
	private javax.swing.JTextField jIdtxt;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JButton jb_delete;
	private javax.swing.JButton jb_modify;
	private javax.swing.JTextField jbookTypeNameTxt;
	// End of variables declaration//GEN-END:variables

}